Add MangaMint
Paperback-iOS/extensions-foreign pull request #24
Opened 2021-04-13 18:50 UTC by nar1n

2021-04-13 21:44 UTC, AdrienSeon requested changes
Here is a first review.
I'll PR a test file into your repo so that you can implement it.

2021-04-13 21:44 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +    }
As we talked about on discord, if you can remove the while and use the `requestManager` to retry requests if possible.
I tested it locally, seemed to work fine.

2021-04-13 21:44 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +          chapNum: Number(chapter["chapter_title"].replace(/^\D+/, '')),
`chapNum` seems to return `Nan`.

2021-04-13 21:44 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +  async getChapterDetails(mangaId: string, chapterId: string): Promise<ChapterDetails> {
Can't really test since `chapNum` is `NaN`.

2021-04-13 21:44 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +    }
As we talked about on discord, if you can remove the while and use the `requestManager` to retry requests if possible.
I tested it locally, seemed to work fine.

2021-04-13 21:44 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +  async searchRequest(searchQuery: SearchRequest, metadata: any): Promise<PagedResults> {
Searches from the API seem to always return a maximum of 20 results, do you know if you can query the next results and so implement the `page` `metadata`?

2021-04-16 23:27 UTC, AdrienSeon requested changes

2021-04-16 23:27 UTC, AdrienSeon commented on src/tests/MangaMint.test.ts
> +
We could add this to the tests too

```js
it("Testing home page results for POPULAR MANGA titles", async () => {
    const results = await wrapper.getViewMoreItems(source, "popular", {page:1}, 1);
    const resultsWithPagedData = await wrapper.getViewMoreItems(source, "popular", {page:3}, 1);

    expect(results, "No results for page 1 for this section").to.exist;
    expect(resultsWithPagedData, "No results for page 3 for this section").to.exist;

    const data = results![0];

    expect(data.id, "No ID present").to.exist;
    expect(data.image, "No image present").to.exist;
    // Ensure that we can resolve the image
    const promises: Promise<void>[] = [];
    promises.push(
        axios.get(data.image).then((imageResult: { status: any }) => {
            expect(imageResult.status).to.equal(200);
        })
    );
    await Promise.all(promises);
    expect(data.title.text, "No title present").to.exist;
});
```

2021-04-16 23:27 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +        }
There are some artefact due to some duplicated mangas in the view while scrolling.

Maybe you could do something like this to prevent this from happening :
```js
async getViewMoreItems(homepageSectionId: string, metadata: any): Promise<PagedResults | null> {
    let page: number = metadata?.page ?? 1;
    let mangaTiles: MangaTile[] = [];
    let mData = undefined;

    const request = createRequestObject({
        url: `${MANGAMINT_API_BASE}/manga/popular/${page}`,
        method: "GET",
    });

    const response = await this.requestManager.schedule(request, 3);
    const result = typeof response.data === "string" ? JSON.parse(response.data) : response.data;

    for (const manga of result["manga_list"]) {
        if (!this.getViewMoreItemsCollectedIds.includes(manga["endpoint"])) {
            mangaTiles.push(
                createMangaTile({
                    id: manga["endpoint"],
                    image: manga["thumb"],
                    title: createIconText({ text: manga["title"] }),
                })
            );
            this.getViewMoreItemsCollectedIds.push(manga["endpoint"]);
        }
    }
```

2021-04-16 23:27 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +            )
There is some artifact due to some duplicated mangas in the view while scrolling.

Maybe you could do something like this to prevent this from happening :
```js
if (!this.getViewMoreItemsCollectedIds.has(manga["endpoint"])) {
    mangaTiles.push(
        createMangaTile({
            id: manga["endpoint"],
            image: manga["thumb"],
            title: createIconText({ text: manga["title"] }),
        })
    );
    this.getViewMoreItemsCollectedIds.add(manga["endpoint"]);
}
```

While adding `private getViewMoreItemsCollectedIds: Set<string> = new Set();` to the class

Same thing for the `searchRequest` method, if possible.

2021-04-16 23:27 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +    }
I don't really see the point of this method since we're querying an API but I can be wrong.

2021-04-16 23:28 UTC, AdrienSeon commented
Thank you for the fixes, just some more that I found and we should be good to go!

2021-04-17 10:06 UTC, nar1n commented on src/MangaMint/MangaMint.ts
> +            desc: mangaDetails["synopsis"]
Fixed by returning the string after the tab delimiters as that is the more complete synopsis.

2021-04-17 10:06 UTC, nar1n commented on src/MangaMint/MangaMint.ts
> +        }
That is correct, I have included the comments now.

2021-04-17 10:06 UTC, nar1n commented on src/MangaMint/MangaMint.ts
> +        if (page <= 9) {
Changed to 29.

2021-04-17 10:06 UTC, nar1n commented on src/tests/MangaMint.test.ts
> +
Added, thank you.

2021-04-17 10:07 UTC, nar1n commented on src/MangaMint/MangaMint.ts
> +            )
Added checks for duplicate ids in both view more and search.

2021-04-17 10:07 UTC, nar1n commented on src/MangaMint/MangaMint.ts
> +    }
Removed.

2021-04-17 12:26 UTC, AdrienSeon approved these changes

2021-04-17 12:27 UTC, AdrienSeon commented
Good for me, thank you for the fixes, I'll let you merge when you're ready!

2021-04-17 12:29 UTC, AdrienSeon commented on src/MangaMint/MangaMint.ts
> +        if (page <= 9) {
Oh, you did this to prevent the user to keep trying to load even if there was no more data?
Got it, good for me!

2021-04-17 12:36 UTC, merged