Add ManaToki
Paperback-iOS/extensions-foreign pull request #26
Opened 2021-04-13 20:03 UTC by nar1n

2021-04-17 00:17 UTC, AdrienSeon requested changes
Source looking really good fully tested and working great, just have to talk about the `filterUpdatedManga` method (cf. my comment in the review).

@ConradWeiser Could we have your opinion on the matter?

2021-04-17 00:17 UTC, AdrienSeon commented on src/ManaToki/ManaToki.ts
> +    async filterUpdatedManga(mangaUpdatesFoundCallback: (updates: MangaUpdates) => void, time: Date, ids: string[]): Promise<void> {
I got [IP banned](https://discord.com/channels/673606787290759230/705193595715452958/832767531454169108) from 2 different IPs while testing the method, I don't know if we should really implement it or create a really slow `requestManager` maybe.
I'll do more tests if when I'm unbanned if I ever am...

2021-04-17 00:17 UTC, AdrienSeon commented on src/tests/ManaToki.test.ts
> +
Could you add these tests for the next time we're testing this source ?

```js
it("Testing home page results for 최신화", async () => {
    const resultsPage1 = await wrapper.getViewMoreItems(source, "list", { page: 1 }, 1);
    const resultsPage3 = await wrapper.getViewMoreItems(source, "list", { page: 3 }, 1);

    expect(resultsPage1, "No results for page 1 for this section").to.exist;
    expect(resultsPage3, "No results for page 3 for this section").to.exist;
    expect(resultsPage1, "Page 1 and 3 are the same").to.not.be.eql(resultsPage3);

    const data = resultsPage1![0];

    expect(data.id, "No ID present").to.exist;
    expect(data.image, "No image present").to.exist;
    expect(data.title.text, "No title present").to.exist;
});

it("Testing home page results for 만화목록", async () => {
    const resultsPage1 = await wrapper.getViewMoreItems(source, "list", { page: 1 }, 1);
    const resultsPage3 = await wrapper.getViewMoreItems(source, "list", { page: 3 }, 1);

    expect(resultsPage1, "No results for page 1 for this section").to.exist;
    expect(resultsPage3, "No results for page 3 for this section").to.exist;
    expect(resultsPage1, "Page 1 and 3 are the same").to.not.be.eql(resultsPage3);

    const data = resultsPage1![0];

    expect(data.id, "No ID present").to.exist;
    expect(data.image, "No image present").to.exist;
    expect(data.title.text, "No title present").to.exist;
});

it("Testing Notifications", async () => {
    const updates = await wrapper.filterUpdatedManga(source, new Date("2021-03-26"), [mangaId]);

    expect(updates, "No server response").to.exist;
    expect(updates, "Empty server response").to.not.be.empty;
    expect(updates[0].ids, "No updates").to.not.be.empty;
});
```

2021-04-17 09:18 UTC, nar1n commented on src/tests/ManaToki.test.ts
> +
Added, thank you.

2021-04-23 05:02 UTC, ConradWeiser commented on src/ManaToki/ManaToki.ts
> +    async filterUpdatedManga(mangaUpdatesFoundCallback: (updates: MangaUpdates) => void, time: Date, ids: string[]): Promise<void> {
The first test I ran also IP banned me. I switched to a VPN and tried changing the requests per second from `2` to `1`, and still got IP banned with this given test case.

I think this method should be commented out.

2021-04-23 05:03 UTC, ConradWeiser requested changes
As stated in a discussion above, the update function is verified to cause IP bans. 
Comment that out for now, and I think this is good to go!

2021-04-24 09:55 UTC, AdrienSeon requested changes

2021-04-24 09:55 UTC, AdrienSeon commented on src/ManaToki/ManaToki.ts
> +}
Last thing that I didn't catch earlier, sorry, could you add the source language as a tag 
```js
sourceTags: [
        {
            text: "Korean",
            type: TagType.GREY
        }
    ]
```
Other that that good to go for me!

2021-04-24 13:35 UTC, Aur0raN reviewed
Tested locally and I see no issues so far, Search and Discover works fine. Scrolled through a few manga as well.

2021-04-24 13:36 UTC, AdrienSeon approved these changes

2021-04-26 00:12 UTC, ConradWeiser approved these changes
Taking another pass on a local device, this checks out and works great! Thank you for the attention!

2021-04-26 01:02 UTC, merged